### ISSUE TITLE
java.lang.RuntimeException in version 4.7.1

### ISSUE THREAD

**Issue by vipul-careers360** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#16]
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NoSuchFieldError: No static field PRODUCT of type Ljava/lang/String; in class Landroid/os/Build; or its superclasses (declaration of 'android.os.Build' appears in /system/framework/framework.jar)
at com.appsflyer.AppsFlyerLib.getUniquePsuedoID(MyApplication:2020)
at com.appsflyer.AppsFlyerLib.callStatsBackground(MyApplication:726)
at com.appsflyer.AppsFlyerLib.access$002(MyApplication:66)
at com.appsflyer.AppsFlyerLib$1.onBecameBackground(MyApplication:293)
at com.appsflyer.Foreground$1.doInBackground(MyApplication:163)
at com.appsflyer.Foreground$1.doInBackground(MyApplication:151)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by sokoloff06** [comment]
Hi!

We are closing this issue due to a lack of activity. Please feel free to re-open and let us know if that is still relevant.

Thank you!
