### ISSUE TITLE
My app crashes at startup

### ISSUE THREAD

**Issue by hugojobe** [AppsFlyerSDK/AdobeAirExtension-AppsFlyer#23]
Hello,
I built an app with android studio but when I launch it on my phone, there is an error. Here is the error log provided by android studio. Can you help me please ?

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hj.lilo, PID: 31948
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.hj.lilo/com.hj.lilo.MainActivity}: java.lang.IllegalAccessException: java.lang.Class<com.hj.lilo.MainActivity> is not accessible from java.lang.Class<android.app.AppComponentFactory>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7078)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.IllegalAccessException: java.lang.Class<com.hj.lilo.MainActivity> is not accessible from java.lang.Class<android.app.AppComponentFactory>
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3015)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3264) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7078) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
I/Process: Sending signal. PID: 31948 SIG: 9
Process 31948 terminated.

**Comment by sokoloff06** [comment]
Hi @Danbo84 !

According to the stack trace it doesn't seem to be related to our SDK:

`Caused by: java.lang.IllegalAccessException: java.lang.Class<com.hj.lilo.MainActivity> is not accessible from java.lang.Class<android.app.AppComponentFactory>`

Can you remove our SDK and see if the issue persists?

If removing the SDK solves the issue, please reach out to support@appsflyer.com with the stack trace and we will do our best to assist.
